# Generated by Django 4.0.3 on 2022-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlEncurtHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url original')),
                ('slug', models.CharField(max_length=7, verbose_name='slug da url')),
            ],
        ),
    ]
