# Generated by Django 4.0.3 on 2022-04-21 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google')], max_length=10, verbose_name='Pixel')),
                ('plataforma', models.CharField(choices=[('pageview', 'PageView'), ('checkout', 'InitiateCheckout'), ('addtocart', 'AddToCart'), ('viewcontent', 'ViewContent')], max_length=20, verbose_name='Evento')),
                ('pixel_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='id do pixel')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pixel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encurtadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('urlr', models.URLField(verbose_name='url original')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='Url Atalho')),
                ('acessos', models.IntegerField(default=0)),
                ('plataform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pixel', verbose_name='Pixel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
