# Generated by Django 4.0.3 on 2022-04-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google')], max_length=10, verbose_name='plataforma')),
                ('pixel_id', models.CharField(max_length=30, verbose_name='id do pixel')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Pixel')),
            ],
        ),
        migrations.CreateModel(
            name='Encurtadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('urlr', models.URLField(verbose_name='url original')),
                ('slug', models.CharField(max_length=7, unique=True, verbose_name='slug da url')),
                ('plataform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pixel')),
            ],
        ),
    ]
