# Generated by Django 4.0.3 on 2022-04-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlencurthome',
            old_name='url',
            new_name='urlr',
        ),
        migrations.AlterField(
            model_name='urlencurthome',
            name='slug',
            field=models.CharField(max_length=7, unique=True, verbose_name='slug da url'),
        ),
    ]
